-- Reset User Badges
DELETE FROM User_Badges;

-- Module 1: Nutrition Basics
UPDATE Lessons SET content = 'Nutrition is the biochemical and physiological process by which an organism uses food to support its life. It provides organisms with nutrients, which can be metabolized to create energy and chemical structures. Failure to obtain sufficient nutrients causes malnutrition. Nutritional science is the study of nutrition, though it typically emphasizes human nutrition.' WHERE lesson_order = 1 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Nutrition Basics' LIMIT 1);
UPDATE Lessons SET content = 'A balanced diet provides all the essential nutrients your body needs to function correctly. It includes a variety of foods from all food groups in the right proportions. A balanced diet typically includes a mix of five food groups: vegetables, fruits, grains, proteins, and dairy. Balancing these groups ensures that the body receives a broad spectrum of nourishment.' WHERE lesson_order = 2 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Nutrition Basics' LIMIT 1);
UPDATE Lessons SET content = 'The five main food groups are the building blocks of a healthy diet. 1. Fruits: Rich in vitamins and fiber. 2. Vegetables: Provide essential minerals and antioxidants. 3. Grains: Source of energy and B-vitamins. 4. Protein: Essential for growth and repair. 5. Dairy: Crucial for bone health through calcium and vitamin D.' WHERE lesson_order = 3 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Nutrition Basics' LIMIT 1);
UPDATE Lessons SET content = 'Nutrition labels provide important information about the nutritional content of packaged foods. Learn to read serving sizes, calories, and key nutrients like fats, grains, and proteins. One key element is the % Daily Value (%DV), which tells you how much a nutrient in a serving contributes to a daily diet.' WHERE lesson_order = 4 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Nutrition Basics' LIMIT 1);
UPDATE Lessons SET content = 'Portion control is the practice of understanding how much food is being consumed and ensuring it aligns with your energy needs. Effective strategies include using smaller plates, measuring servings with common objects, and being mindful of hunger cues. By mastering portions, you can enjoy a variety of foods without over-consuming calories.' WHERE lesson_order = 5 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Nutrition Basics' LIMIT 1);

-- Module 2: Balanced Diet
UPDATE Lessons SET content = 'The plate method is a simple and effective visual guide for creating balanced, nutritious meals. Fill half of your plate with non-starchy vegetables, one quarter with lean protein, and one quarter with whole grains. This proportion naturally manages calorie intake while ensuring a spectrum of nutrients at every meal.' WHERE lesson_order = 1 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Balanced Diet' LIMIT 1);
UPDATE Lessons SET content = 'Effective meal planning is a cornerstone of a healthy lifestyle. It involves thinking ahead about what you will eat for the week, which helps avoid impulsive, less nutritious choices. Start by auditing your pantry, choosing a few recipes, and creating a structured shopping list. Batch cooking can save hours during the work week.' WHERE lesson_order = 2 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Balanced Diet' LIMIT 1);
UPDATE Lessons SET content = 'Snacks can be part of a healthy diet when chosen wisely. Opt for nutrient-dense options like fruits, vegetables with hummus, nuts, or yogurt instead of processed snacks. Smart snacking helps maintain energy levels between meals and prevents overeating during main meal times.' WHERE lesson_order = 3 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Balanced Diet' LIMIT 1);
UPDATE Lessons SET content = 'Learn strategies for making healthy choices when dining out. Tips include checking nutrition information beforehand, choosing grilled over fried options, and being mindful of portion sizes. You can also ask for dressings on the side and share large portions with friends to manage calorie intake.' WHERE lesson_order = 4 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Balanced Diet' LIMIT 1);
UPDATE Lessons SET content = 'Eating healthy does not have to be expensive. Learn to choose affordable nutritious foods like beans, lentils, and seasonal produce. Shopping seasonally, minimizing food waste, and cooking at home more often can significantly lower your grocery bills while still supporting your nutritional goals.' WHERE lesson_order = 5 AND module_id = (SELECT module_id FROM Modules WHERE title = 'Balanced Diet' LIMIT 1);
